# Generated by Django 5.2.5 on 2025-10-18 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_course_semester_course_year_of_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='highest_qualification',
            field=models.CharField(blank=True, choices=[('BACHELORS', 'Bachelor’s Degree'), ('MASTERS', 'Master’s Degree'), ('PHD', 'PhD'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.program'),
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertises', to='accounts.program')),
            ],
            options={
                'unique_together': {('program', 'name')},
            },
        ),
    ]
