# Generated by Django 5.2.5 on 2025-10-19 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_course_user_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='program',
        ),
        migrations.AddField(
            model_name='user',
            name='contributor_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributors', to='accounts.program'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.program'),
        ),
        migrations.AlterField(
            model_name='user',
            name='domain_of_expertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experts', to='accounts.expertise'),
        ),
    ]
