# Generated by Django 5.2.5 on 2025-10-20 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_program_user_contributor_program_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contributor_program',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_program',
        ),
        migrations.AddField(
            model_name='expertise',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='expertises', to='accounts.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.program'),
        ),
    ]
