# Generated by Django 5.2.5 on 2025-10-21 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_contributor_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='accounts.course')),
            ],
        ),
    ]
