# Generated by Django 5.2.5 on 2025-10-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_courseobjective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='domain_of_expertise',
        ),
        migrations.AddField(
            model_name='user',
            name='domain_of_expertise',
            field=models.ManyToManyField(blank=True, related_name='experts', to='accounts.expertise'),
        ),
    ]
