# Generated by Django 5.2.5 on 2025-10-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_domain_of_expertise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.CharField(default='No description available', max_length=500),
        ),
    ]
