# Generated by Django 5.2.5 on 2025-10-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_assessment_question_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='created_by',
            new_name='contributor_id',
        ),
        migrations.RenameField(
            model_name='contentscore',
            old_name='parameter1',
            new_name='accuracy',
        ),
        migrations.RenameField(
            model_name='contentscore',
            old_name='parameter2',
            new_name='clarity',
        ),
        migrations.RenameField(
            model_name='contentscore',
            old_name='parameter3',
            new_name='completeness',
        ),
        migrations.AddField(
            model_name='contentscore',
            name='enagagement',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
