# Generated by Django 5.2.5 on 2025-10-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_created_by_assessment_contributor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year_of_study',
            field=models.CharField(blank=True, null=True),
        ),
    ]
