# Generated by Django 5.2.5 on 2025-10-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_course_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.CharField(default='No description available', max_length=10000),
        ),
    ]
