# Generated by Django 5.2.5 on 2025-11-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_forumtopic_dmthread_dmmessage_forumquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
